from enum import Enum


class Category(Enum):
    Arcanes = "Arcanes"
    Arch_Gun = "Arch-Gun"
    Arch_Melee = "Arch-Melee"
    Archwing = "Archwing"
    Enemy = "Enemy"
    Fish = "Fish"
    Gear = "Gear"
    Glyphs = "Glyphs"
    Melee = "Melee"
    Misc = "Misc"
    Mods = "Mods"
    Node = "Node"
    Pets = "Pets"
    Primary = "Primary"
    Quests = "Quests"
    Relics = "Relics"
    Resources = "Resources"
    Secondary = "Secondary"
    Sentinels = "Sentinels"
    Sigils = "Sigils"
    Skins = "Skins"
    Warframes = "Warframes"
