"""empty message

Revision ID: 58d3fa91e9fc
Revises: b8b5a1aa4ab5
Create Date: 2024-01-31 15:56:00.097377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58d3fa91e9fc'
down_revision: Union[str, None] = 'b8b5a1aa4ab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('glyph_items', 'excludeFromCodex',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('glyph_items', 'excludeFromCodex',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
